/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasAntigas;

import Codigos.Conexao;
import Codigos.Pessoa;
import Codigos.Responsavel;
import Codigos.Telefone;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.AccessibleRole;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Renan
 */
public class TelaCadastro2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro2
     */
    public TelaCadastro2() {
        initComponents();
        jBCad.setEnabled(false);
        jCSerie.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTFCodigoTel1 = new javax.swing.JTextField();
        jBExTel1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jCTipo = new javax.swing.JComboBox<>();
        jFRg = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jFCPF = new javax.swing.JFormattedTextField();
        jTNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBCad = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jTCompl = new javax.swing.JTextField();
        jBEdit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBDel = new javax.swing.JButton();
        jFDTNasc = new javax.swing.JFormattedTextField();
        jBLimp = new javax.swing.JButton();
        jTFNome = new javax.swing.JTextField();
        jTRua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTCidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTbairro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jCSerie = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPSenha = new javax.swing.JPasswordField();
        jLFoto = new javax.swing.JLabel();
        jBAddImagem = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTFCodigoTel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jFTelefone = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jTFDescrTel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaTel = new javax.swing.JTable();
        jBAddTel = new javax.swing.JButton();
        jBBuscarTel = new javax.swing.JButton();
        jBExTel = new javax.swing.JButton();
        jBLimparTel = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTFCodigoTel2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTFCodigoAluno = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTFDescrRespo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelaRespo = new javax.swing.JTable();
        jTFNomeRespo = new javax.swing.JTextField();
        jBAddR = new javax.swing.JButton();
        jBBuscarR = new javax.swing.JButton();
        jBExR = new javax.swing.JButton();
        jBLimparR = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("RA:");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("RA:");

        jTFCodigoTel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFCodigoTel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTFCodigoTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoTel1ActionPerformed(evt);
            }
        });

        jBExTel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBExTel1.setText("Excluir");
        jBExTel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("CPF:");

        jCTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Aluno", "Responsavel", "Professor", "Funcionário" }));
        jCTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTipoActionPerformed(evt);
            }
        });

        jFRg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFRg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Numero:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("RG:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Tipo:");

        jFCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFCPF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTNum.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Codigo:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Complemento:");

        jTFCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBCad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBCad.setText("Cadastrar");
        jBCad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadActionPerformed(evt);
            }
        });

        jBBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTCompl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTCompl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBEdit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBEdit.setText("Editar");
        jBEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");

        jBDel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBDel.setText("Deletar");
        jBDel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDelActionPerformed(evt);
            }
        });

        jFDTNasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFDTNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFDTNasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jBLimp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBLimp.setText("Limpar");
        jBLimp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpActionPerformed(evt);
            }
        });

        jTFNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTRua.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTRua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Cidade:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Data de Nascimento:");

        jTCidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTCidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("UF:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("CEP:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Bairro:");

        jTbairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTbairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Série:");

        jCSerie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "1º Ano", "2º Ano", "3º Ano", "4º Ano", "5º Ano", "6º Ano", "7º Ano", "8º Ano", "9º Ano", "1º Colegial", "2º Colegial", "Colegial 3" }));
        jCSerie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSerieActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Senha:");

        jTFEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Email:");

        jPSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBAddImagem.setText("IMAGEM");
        jBAddImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddImagemActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Endereço:");

        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jBCad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBDel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBLimp, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFDTNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBAddImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTRua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTbairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFRg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTCompl)
                            .addComponent(jTNum, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jFCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jPSenha)
                            .addComponent(jTextField1))))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFDTNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBAddImagem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jTNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFRg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLimp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCad, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Cadastro", new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONPerfil.png")), jPanel1); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Nome:");

        jTFCodigoTel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFCodigoTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Telefone:");

        jFTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Descrição:");

        jTFDescrTel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFDescrTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTabelaTel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabelaTel);

        jBAddTel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBAddTel.setText("Adicionar");
        jBAddTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBAddTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddTelActionPerformed(evt);
            }
        });

        jBBuscarTel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBBuscarTel.setText("Buscar");
        jBBuscarTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBBuscarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarTelActionPerformed(evt);
            }
        });

        jBExTel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBExTel.setText("Excluir");
        jBExTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBExTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExTelActionPerformed(evt);
            }
        });

        jBLimparTel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBLimparTel.setText("Limpar");
        jBLimparTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBLimparTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparTelActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Codigo:");

        jTFCodigoTel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFCodigoTel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(298, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFDescrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCodigoTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCodigoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAddTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBExTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBLimparTel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscarTel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCodigoTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCodigoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFDescrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAddTel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscarTel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBExTel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLimparTel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jTabbedPane1.addTab("Telefone", new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONTelefone.png")), jPanel2); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("RA:");

        jTFCodigoAluno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFCodigoAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Descrição:");

        jTFDescrRespo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFDescrRespo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Nome:");

        jTabelaRespo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTabelaRespo);

        jTFNomeRespo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFNomeRespo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBAddR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBAddR.setText("Adicionar");
        jBAddR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBAddR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddRActionPerformed(evt);
            }
        });

        jBBuscarR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBBuscarR.setText("Buscar");
        jBBuscarR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBBuscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarRActionPerformed(evt);
            }
        });

        jBExR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBExR.setText("Excluir");
        jBExR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBExR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExRActionPerformed(evt);
            }
        });

        jBLimparR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBLimparR.setText("Limpar");
        jBLimparR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBLimparR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTFNomeRespo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBExR, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFDescrRespo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFCodigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addComponent(jBAddR, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBBuscarR, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLimparR, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAddR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscarR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBExR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLimparR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCodigoAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFDescrRespo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNomeRespo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Responsaveis", new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONResponsavel.png")), jPanel3); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 640));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logoPequeno.png"))); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, 60));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroundLADO.png"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 801, 154));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadActionPerformed
        // TODO add your handling code here:
        Pessoa a = new Pessoa();
        Conexao c = new Conexao();
        
  
        //Insere os dados preenchidos pelo usuario nas variaveis
      //  a.setRA(Integer.parseInt(jTFCodigo.getText()));
        a.setNome(jTFNome.getText());
        a.setDataNasc(jFDTNasc.getText());
        a.setTipo((String) jCTipo.getSelectedItem());
        a.setRua(jTRua.getText());
        a.setNumero(jTNum.getText());
        a.setComplemento(jTCompl.getText());
        a.setBairro(jTbairro.getText());
        a.setCidade(jTCidade.getText());
   //     a.setUf((String) jComUF.getSelectedItem());
        a.setRg(jFRg.getText());
        a.setCpf(jFCPF.getText());
        a.setSerie((String) jCSerie.getSelectedItem());
        a.setEmail(jTFEmail.getText());
        a.setSenha(jPSenha.getText());
        
        
        //Comando que cadastra no banco de dados os valores lidos (Tabela: pcc_tb_pessoas)
        String cadastrar = "insert into pcc_tb_pessoas("
        + "Pess_ST_Nome, Pess_ST_Rua, Pess_ST_Numero, Pess_ST_Complemento, "
        + "Pess_ST_Bairro, Pess_ST_Cidade, Pess_ST_UF, Pess_ST_DataNasc, "
        + "Pess_ST_Rg, Pess_ST_CPF, Pess_ST_Tipo, Pess_ST_Email, Pess_ST_Senha, Pess_JPG_Foto) values "
        + "( '"+a.getNome()+"', '"+a.getRua()+"', '"+a.getNumero()+"',"
        + " '"+a.getComplemento()+"', '"+a.getBairro()+"', '"+a.getCidade()+"', "
    //    + "'"+a.getUf()+"',"
                + " '"+a.getDataNasc()+"', '"+a.getRg()+"', "
        + "'"+a.getCpf()+"', '"+a.getTipo()+"','"+a.getEmail()+"', '"+a.getSenha()+"', '"+a.getFoto()+"');";

        
        try {
            c.conectar();
                if(c.runSql(cadastrar)){
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
//                 if(a.getTipo().equals("Aluno")){
//            String CadAluS = "call proc_CadastraAlunoSerie('"+a.getRA()+"' , '"+a.getSerie()+"');";
//            c.runSql(CadAluS);
//        }
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivel cadastrar!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }
//            
//       

                        

    }//GEN-LAST:event_jBCadActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        Pessoa a = new Pessoa();
        Conexao c = new Conexao();
        
      int  cod = Integer.parseInt(jTFCodigo.getText());

        //Comando que faz uma busca no banco de dados de acordo com o Codigo da pessoas 
        String buscar= "select * from pcc_tb_pessoas where pess_int_codigo = '"+cod+"';";

        try {
            c.conectar();
            a=c.pesquisa_aluno(buscar);
            if(!c.equals(null)){
                //Insere os valores encotrados no campos correspondentes 
                jTFNome.setText(a.getNome());
                jTRua.setText(a.getRua());
                jTNum.setText(a.getNumero());
                jTCidade.setText(a.getCidade());
                jTbairro.setText(a.getBairro());
                jFDTNasc.setText(a.getDataNasc());
                jTCompl.setText(a.getComplemento());
         //       jComUF.setSelectedItem(a.getUf());
                jFRg.setText(a.getRg());
                jFCPF.setText(a.getCpf());
                jCTipo.setSelectedItem(a.getTipo());
                jTFEmail.setText(a.getEmail());
                jPSenha.setText(a.getSenha());
                //

            }else{
                JOptionPane.showMessageDialog(null, "RA não encontrado");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditActionPerformed
        // TODO add your handling code here:
        Pessoa a = new Pessoa();
        Conexao c = new Conexao();

         //Insere os dados preenchidos pelo usuario nas variaveis
        a.setRA(Integer.parseInt(jTFCodigo.getText()));
        a.setNome(jTFNome.getText());
        a.setRua(jTRua.getText());
        a.setNumero(jTNum.getText());
        a.setBairro(jTbairro.getText());
        a.setComplemento(jTCompl.getText());
     //   a.setUf((String) jComUF.getSelectedItem());
        a.setCidade(jTCidade.getText());
        a.setDataNasc(jFDTNasc.getText());
        a.setRg(jFRg.getText());
        a.setCpf(jFCPF.getText());
        a.setTipo((String) jCTipo.getSelectedItem());
        a.setEmail(jTFEmail.getText());
        a.setSenha(jPSenha.getText());

        //Comando realiza atualizações/modificações na tabela de pessoas de acordo com o codigo do ususario
        String editar = "update pcc_tb_pessoas set pess_st_nome = '"+a.getNome()+"',"
        + " pess_st_rua = '"+a.getRua()+"', "
        + "pess_st_numero = '"+a.getNumero()+"', "
        + "pess_st_complemento = '"+a.getComplemento()+"', "
        + "pess_st_bairro = '"+a.getBairro()+"', "
        + "pess_st_cidade = '"+a.getCidade()+"',"
    //    + " pess_st_UF ='"+ a.getUf()+"', "
        + "pess_st_DataNasc = '"+a.getDataNasc()+"', "
        + "pess_st_rg = '"+a.getRg()+"', pess_st_cpf = '"+a.getCpf()+"',"
        + " pess_st_tipo = '"+a.getTipo()+"', pess_JPG_Foto = '"+null+"', "
        + "pess_st_email ='"+a.getEmail()+"', pess_st_senha= '"+a.getSenha()+"'"
        + " where pess_int_codigo = '"+a.getRA()+"';";

        try {
            c.conectar();
            if(c.runSql(editar)){
                JOptionPane.showMessageDialog(null, "Editado com sucesso");
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivel editar");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBEditActionPerformed

    private void jBDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDelActionPerformed
        // TODO add your handling code here:
        Conexao c = new Conexao();

        int cod = Integer.parseInt(jTFCodigo.getText());

        //Comando que realiza a exclusão de um cadastro com base no codigo da pessoa
        String del = "delete from pcc_tb_pessoas where pess_int_codigo = '"+cod+"';";

        try {
            c.conectar();
            if(c.runSql(del)){
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivel excluir");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBDelActionPerformed

    private void jBLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpActionPerformed
        // TODO add your handling code here:
        //Metodo que "Limpa" todas as caixas de texto
        
        jTFCodigo.setText(null);
        jTFNome.setText(null);
        jTRua.setText(null);
        jTNum.setText(null);
        jTCidade.setText(null);
        jTbairro.setText(null);
        jFDTNasc.setText(null);
        jTCompl.setText(null);
     //   jComUF.setSelectedItem("Selecione...");
        jFRg.setText(null);
        jFCPF.setText(null);
        jCTipo.setSelectedItem("Selecione...");
        jTFEmail.setText(null);
        jPSenha.setText(null);
        jCSerie.setSelectedItem("Selecione...");
     

    }//GEN-LAST:event_jBLimpActionPerformed

    private void jTFCodigoTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoTel1ActionPerformed

    private void jBAddTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddTelActionPerformed
        // TODO add your handling code here:
        Telefone t = new Telefone();
        Conexao c = new Conexao();
        //Insere os dados preenchidos pelo usuario nas variaveis
        t.setNome((jTFCodigoTel.getText()));
        t.setRA(Integer.parseInt(jTFCodigoTel2.getText()));
        t.setTelefone(jFTelefone.getText());
        t.setDesc(jTFDescrTel.getText());
        
        //Comando que cadastra no banco de dados os valores lidos (Tabela: pcc_tb_telefone) 
        //correspondente com um codigo de usuario
        
        String cadTel = "call proc_CadTelefone('"+t.getNome()+"', '"+t.getTelefone()+"', '"+t.getDesc()+"');";
        
        try {
            c.conectar();
            if(c.runSql(cadTel)){
                JOptionPane.showMessageDialog(null, "Telefone cadastrado com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Telefone não cadastrado!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        jFTelefone.setText(null);
        jTFDescrTel.setText(null);
        
        
    }//GEN-LAST:event_jBAddTelActionPerformed

    private void jBBuscarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarTelActionPerformed
        // TODO add your handling code here:
        Telefone t = new Telefone();
        Telefone x = new Telefone();
        Conexao c = new Conexao();
        int linha = 1;
        
        int cod = Integer.parseInt(jTFCodigoTel2.getText());

        //Comando que realiza uma contagem de dados inseridos na tabela de telefone de
        //acordo com o codigo do usuario e esse valor é inserido na variavel (tamanho) 
        String tamanho= "select count(Tel_INT_Codigo) from pcc_tb_telefone where pess_int_codigo = "+cod+";";
        
        try {
            c.conectar();
            
            x=c.pesquisa_tamtelefone(tamanho);
            if(!c.equals(null)){
                do{
                    
                //Comando que realiza uma busca na tabela de telefone com base em um codigo de pessoa
                String buscar= "select * from pcc_tb_telefone where pess_int_codigo = "+cod+" and Tel_INT_Codigo = "+linha+";";
                t=c.pesquisa_telefone(buscar);
                //Insere todos os telefones encotrados no banco na tabela
                jTabelaTel.setValueAt(t.getTelefone(), linha-1 , 0);
                jTabelaTel.setValueAt(t.getDescricao(), linha-1, 1);
                linha++;
                }while (linha <= x.getTamanhoTel());//Determina quantas vezes a impressão dos valores encotrados deve ser feita         
            }
            
               } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jBBuscarTelActionPerformed

    private void jBLimparTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparTelActionPerformed
        // TODO add your handling code here:
        
  LimpartelaTel(); 
  
    }//GEN-LAST:event_jBLimparTelActionPerformed

    private void jBExTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExTelActionPerformed
        // TODO add your handling code here:
        Conexao c = new Conexao();
        Telefone t = new Telefone();
        
        t.setTelefone(jFTelefone.getText());
        t.setRA(Integer.parseInt(jTFCodigoTel2.getText()));
         //Comando que realiza a exclusão de um telefone com base no codigo da pessoa e no numero de telefone
        String del = "delete from pcc_tb_telefone where tel_st_numero = '"+t.getTelefone()+"'"
                + " and pess_int_codigo ='"+t.getRA()+"';";
        
        try {
            c.conectar();
            if(c.runSql(del)){
                JOptionPane.showMessageDialog(null, "Deletado com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivvel excluir");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }
        LimpartelaTel();
    }//GEN-LAST:event_jBExTelActionPerformed

    private void jCTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTipoActionPerformed
        // TODO add your handling code here:
        
        //Comando que impede o cadastro se não for selecionado algum  Tipo de pessoa (jComboBox Tipo)
        if(!jCTipo.getSelectedItem().equals("Selecione...")){
            jBCad.setEnabled(true);
        }else{
            jBCad.setEnabled(false);
        }
         if(jCTipo.getSelectedItem().equals("Aluno")){
             jCSerie.setEnabled(true);
         }else{
             jCSerie.setEnabled(false);
         }
        
    }//GEN-LAST:event_jCTipoActionPerformed

    private void jCSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCSerieActionPerformed

    private void jBLimparRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparRActionPerformed
        // TODO add your handling code here:
        LimpaTelaRespo();
    }//GEN-LAST:event_jBLimparRActionPerformed

    private void jBExRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExRActionPerformed
        // TODO add your handling code here:
        Responsavel r = new Responsavel();
        Conexao c = new Conexao();

        r.setRA(Integer.parseInt(jTFCodigoAluno.getText()));
        r.setResponsavel(jTFNomeRespo.getText());

        //Comando que realiza uma exclusão na tebela de responsavel baseado no RA do aluno e no nome do responsavel
        String deletar = "delete from pcc_tb_responsavel "
        + "where Alu_INT_Codigo = '"+r.getRA()+"' and "
        + "Resp_INT_Codigo = (select pess_int_codigo "
        + "from pcc_tb_pessoas where Pess_ST_Nome = '"+r.getResponsavel()+"') ;";

        try {
            c.conectar();
            if(c.runSql(deletar)){
                JOptionPane.showMessageDialog(null, "Deletado com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivel excluir");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBExRActionPerformed

    private void jBBuscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarRActionPerformed
        // TODO add your handling code here:
        Responsavel  a = new  Responsavel();
        Responsavel  x = new  Responsavel();
        Conexao c = new Conexao();
        int linha=1;

        int codigo = Integer.parseInt(jTFCodigoAluno.getText());

        //Comando que realiza uma contagem de dados inseridos na tabela de responsavel de
        //acordo com o codigo do usuario e esse valor é inserido na variavel (tamanhoR)
        String tamanhoR = "select count(res_int_codigo) from pcc_tb_responsavel"
        + "  where alu_int_codigo = '"+codigo+"';";

        try {
            c.conectar();

            x= c.pesquisa_tamResponsavel(tamanhoR);
            if(!c.equals(null)){
                do{
                    //Comando que realiza uma busca na tabela de responsavel com base em um codigo de pessoa
                    String buscar= "select a.pess_st_nome, b.res_st_descrição "
                    + "from pcc_tb_pessoas a , pcc_tb_responsavel b where "
                    + "a.Pess_INT_Codigo = b.Resp_INT_Codigo "
                    + "and b.Alu_INT_Codigo = '"+codigo+"' and b.Res_INT_Codigo = '"+linha+"';";

                    a=c.pesquisa_responsavel(buscar);
                    jTabelaRespo.setValueAt(a.getResponsavel(), linha-1 , 0);
                    jTabelaRespo.setValueAt(a.getDescricao(), linha-1, 1);
                    linha++;
                    //JOptionPane.showMessageDialog(this, a.getResponsavel()+a.getDescricao());
                }while (linha <= x.getTamanho());//Determina quantas vezes a impressão dos valores encotrados deve ser feita
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBBuscarRActionPerformed

    private void jBAddRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddRActionPerformed
        // TODO add your handling code here:
        Responsavel r = new Responsavel();
        Conexao c = new Conexao();

        r.setRA(Integer.parseInt(jTFCodigoAluno.getText()));
        r.setResponsavel(jTFNomeRespo.getText());
        r.setDescricao(jTFDescrRespo.getText());

        //Comando que cadastra no banco de dados os valores lidos (Tabela: pcc_tb_responsaveis)
        //correspondente com um codigo de usuario
        String cadres= "call proc_CadResponsavel('"+r.getResponsavel()+"', '"+r.getRA()+"', '"+r.getDescricao()+"');";

        try {
            c.conectar();
            if(c.runSql(cadres)){
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivel cadastrar!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBAddRActionPerformed

    private void jBAddImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddImagemActionPerformed
        // TODO add your handling code here:
        
        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione uma foto"); //Titulo do explorador de arquivos
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY); // Filtro de arquivos
        
        int opc = arquivo.showOpenDialog(this); //Abre o explorador de arquivos
        if(opc == JFileChooser.APPROVE_OPTION){ //Verifica se algo foi selecionado, Se sim...
            File f = new File("Caminho");
            f = arquivo.getSelectedFile();
            
//            /*TALVEZ
            Pessoa p = new Pessoa();
            String caminhoFoto = f.getAbsolutePath();
            p.setFoto(caminhoFoto);
//           
            
            ImageIcon imagem = new ImageIcon(arquivo.getSelectedFile().getPath());
            jLFoto.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(jLFoto.getWidth(), jLFoto.getHeight(), Image.SCALE_DEFAULT)));
            
        }else if(opc == JFileChooser.CANCEL_OPTION){// Se não
            JOptionPane.showMessageDialog(this, "nenhum arquivo selecionado");
        }
        
    }//GEN-LAST:event_jBAddImagemActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro2().setVisible(true);
            }
        });
    }

    public void LimpartelaTel(){
          //Metodo que "Limpa" todas as caixas de texto no painel "Telefone"
        jTFCodigoTel.setText(null);
       jFTelefone.setText(null);
       jTFDescrTel.setText(null);
    }
    public void LimpaTelaRespo() {
        //Metodo que "Limpa" todas as caixas de texto no painel "Responsavel"
        jTFCodigoAluno.setText(null);
        jTFDescrRespo.setText(null);
        jTFNomeRespo.setText(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddImagem;
    private javax.swing.JButton jBAddR;
    private javax.swing.JButton jBAddTel;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBBuscarR;
    private javax.swing.JButton jBBuscarTel;
    private javax.swing.JButton jBCad;
    private javax.swing.JButton jBDel;
    private javax.swing.JButton jBEdit;
    private javax.swing.JButton jBExR;
    private javax.swing.JButton jBExTel;
    private javax.swing.JButton jBExTel1;
    private javax.swing.JButton jBLimp;
    private javax.swing.JButton jBLimparR;
    private javax.swing.JButton jBLimparTel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCSerie;
    private javax.swing.JComboBox<String> jCTipo;
    private javax.swing.JFormattedTextField jFCPF;
    private javax.swing.JFormattedTextField jFDTNasc;
    private javax.swing.JFormattedTextField jFRg;
    private javax.swing.JFormattedTextField jFTelefone;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JTextField jTCompl;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFCodigoAluno;
    private javax.swing.JTextField jTFCodigoTel;
    private javax.swing.JTextField jTFCodigoTel1;
    private javax.swing.JTextField jTFCodigoTel2;
    private javax.swing.JTextField jTFDescrRespo;
    private javax.swing.JTextField jTFDescrTel;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFNomeRespo;
    private javax.swing.JTextField jTNum;
    private javax.swing.JTextField jTRua;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTabelaRespo;
    private javax.swing.JTable jTabelaTel;
    private javax.swing.JTextField jTbairro;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
