/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas2;

import TelasAntigas.TelaCadastro2;
import Codigos.Conexao;
import Codigos.Telefone;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Renan
 */
public class TelaTelefoneInternal extends javax.swing.JInternalFrame {
    private int func;
    private String log;
    private String registroLog;

    public int getFunc() {
        return func;
    }

    public void setFunc(int func) {
        this.func = func;
    }
    /**
     * Creates new form TelaTelefoneInternal
     */
    public TelaTelefoneInternal() {
        initComponents();
        jTabelaTel.setDefaultRenderer(Object.class, new CellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaTel = new javax.swing.JTable();
        jTFCodigoTel = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTFDescrTel = new javax.swing.JTextField();
        jFTelefone = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jBAddTel = new javax.swing.JButton();
        jBBuscarTel = new javax.swing.JButton();
        jBExTel = new javax.swing.JButton();
        jBLimparTel = new javax.swing.JButton();
        jBBusCod = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1367, 700));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Codigo:");

        jTabelaTel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabelaTel);

        jTFCodigoTel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFCodigoTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTFCodigoTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCodigoTelKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Descrição:");

        jTFDescrTel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFDescrTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTFDescrTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFDescrTelKeyTyped(evt);
            }
        });

        jFTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Telefone:");

        jBAddTel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBAddTel.setText("Adicionar");
        jBAddTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBAddTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddTelActionPerformed(evt);
            }
        });

        jBBuscarTel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBBuscarTel.setText("Buscar");
        jBBuscarTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBBuscarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarTelActionPerformed(evt);
            }
        });

        jBExTel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBExTel.setText("Excluir");
        jBExTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBExTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExTelActionPerformed(evt);
            }
        });

        jBLimparTel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBLimparTel.setText("Limpar");
        jBLimparTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBLimparTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparTelActionPerformed(evt);
            }
        });

        jBBusCod.setText("...");
        jBBusCod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBBusCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBusCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTFCodigoTel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBBusCod, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(66, 66, 66)
                        .addComponent(jTFDescrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAddTel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jBBuscarTel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jBExTel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jBLimparTel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFCodigoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBBusCod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(jFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFDescrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAddTel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscarTel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBExTel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLimparTel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(169, 169, 169))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAddTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddTelActionPerformed
      // Verifica se os campos estão preenchidos 
        if(jTFCodigoTel.getText().equals("")||jTFDescrTel.getText().equals("")||jFTelefone.getText().equals("(  )      -    ")){
           JOptionPane.showMessageDialog(this, "Campo(s) não preenchido(s) corretamente");
       }else{
           Telefone t = new Telefone();
        Conexao c = new Conexao();
        //Insere os dados preenchidos pelo usuario nas variaveis
        t.setRA(Integer.parseInt(jTFCodigoTel.getText()));
        t.setTelefone(jFTelefone.getText());
        t.setDesc(jTFDescrTel.getText().toUpperCase());
        
           try {
               c.conectar();
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(TelaTelefoneInternal.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               Logger.getLogger(TelaTelefoneInternal.class.getName()).log(Level.SEVERE, null, ex);
           }
           
        //Verifica se o numero já foi cadastrado
        String verTel = "select count(*) from pcc_tb_telefone where Tel_ST_Numero='"+t.getTelefone()+"';";
        if(c.verifica(verTel) >= 1){
            JOptionPane.showMessageDialog(this, "O telefone já foi cadastrado");
        }else{

        //Comando que cadastra no banco de dados os valores lidos (Tabela: pcc_tb_telefone)
        //correspondente com um codigo de usuario

        String cadTel = "call proc_CadTelefone('"+t.getRA()+"', '"+t.getTelefone()+"', '"+t.getDesc()+"');";

        try {
            c.conectar();
            if(c.runSql(cadTel)){ // Registra na tabela de LOG a ação
                JOptionPane.showMessageDialog(null, "Telefone cadastrado com sucesso!");
                log = "Cadastro de novo telefone para usuário de ID: "+t.getRA()+";";
                registroLog = "insert into pcc_tb_log values(null,"+func+",'"+log+"', default);";
                c.runSql(registroLog);
            }else{
                JOptionPane.showMessageDialog(null, "Telefone não cadastrado!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }

        jFTelefone.setText(null);
        jTFDescrTel.setText(null);
        jBBuscarTel.doClick(); // Executa o botão de buscar
       }}         
    }//GEN-LAST:event_jBAddTelActionPerformed

    private void jBBuscarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarTelActionPerformed
       //Verifica se os campos foram preechidos 
        if(jTFCodigoTel.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nenhum código digitado");
        }else{
        Telefone t = new Telefone();
        Telefone x = new Telefone();
        Conexao c = new Conexao();
        int linha = 1;
        
        int cod = Integer.parseInt(jTFCodigoTel.getText());

        //Comando que realiza uma contagem de dados inseridos na tabela de telefone de
        //acordo com o codigo do usuario e esse valor é inserido na variavel (tamanho)
        String tamanho= "select count(Tel_INT_Codigo) from pcc_tb_telefone where pess_int_codigo = "+cod+";";

        try {
            c.conectar();

            x=c.pesquisa_tamtelefone(tamanho);
            LimpaTabela();
            if(x.getTamanhoTel() == 0){
                JOptionPane.showMessageDialog(this, "Nenhum telefone encontrado!!!");
            }else{
            jTabelaTel.setVisible(true);
            if(!c.equals(null)){
                do{

                    //Comando que realiza uma busca na tabela de telefone com base em um codigo de pessoa
                    String buscar= "select * from pcc_tb_telefone where pess_int_codigo = "+cod+" and Tel_INT_Codigo = "+linha+";";
                    t=c.pesquisa_telefone(buscar);
                    //Insere todos os telefones encotrados no banco na tabela
                    jTabelaTel.setValueAt(t.getTelefone(), linha-1 , 0);
                    jTabelaTel.setValueAt(t.getDescricao(), linha-1, 1);
                    linha++;
                }while (linha <= x.getTamanhoTel());//Determina quantas vezes a impressão dos valores encotrados deve ser feita
            }

        }} catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }//GEN-LAST:event_jBBuscarTelActionPerformed

    private void jBExTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExTelActionPerformed
        // TODO add your handling code here:
        Conexao c = new Conexao();
        Telefone t = new Telefone();

        t.setTelefone(jFTelefone.getText());
        t.setRA(Integer.parseInt(jTFCodigoTel.getText()));
        //É necessário ter no mínimo um telefone cadastrado
        String verificaTel = "select count(*) from pcc_tb_telefone where Pess_INT_Codigo="+t.getRA()+";";
        try {
            c.conectar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaTelefoneInternal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaTelefoneInternal.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(c.verifica(verificaTel) == 1 || c.verifica(verificaTel) == 0){
            JOptionPane.showMessageDialog(this, "É necessário ter no mínimo um telefone cadastrado");
        }else{
        //Comando que realiza a exclusão de um telefone com base no codigo da pessoa e no numero de telefone
        String del = "delete from pcc_tb_telefone where tel_st_numero = '"+t.getTelefone()+"'"
        + " and pess_int_codigo ='"+t.getRA()+"';";

        try {
            c.conectar();
            if(c.runSql(del)){
                JOptionPane.showMessageDialog(null, "Deletado com sucesso!");
                log = "Telefone apagado para usuário de ID: "+t.getRA()+";";
                registroLog = "insert into pcc_tb_log values(null,"+func+",'"+log+"', default);";
                c.runSql(registroLog);
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivvel excluir");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFTelefone.setText(null);
        jTFDescrTel.setText(null);
        jBBuscarTel.doClick();}
    }//GEN-LAST:event_jBExTelActionPerformed

    private void jBLimparTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparTelActionPerformed
        // TODO add your handling code here:

        LimpartelaTel();
    }//GEN-LAST:event_jBLimparTelActionPerformed

    private void jBBusCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBusCodActionPerformed
        // TODO add your handling code here:

        TelaBuscaCodigo t = new TelaBuscaCodigo();
        t.setTipo("");
        t.getCod();
        t.setVisible(true);

    }//GEN-LAST:event_jBBusCodActionPerformed

    private void jTFCodigoTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodigoTelKeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTFCodigoTelKeyTyped

        public class CellRenderer extends DefaultTableCellRenderer {
	public CellRenderer() {
		super();
	}
	public Component getTableCellRendererComponent(JTable table, Object value,
			boolean isSelected, boolean hasFocus, int row, int column) {
		this.setHorizontalAlignment(CENTER);
		return super.getTableCellRendererComponent(table, value, isSelected,
				hasFocus, row, column);
	}
}
        
    private void jTFDescrTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDescrTelKeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isLetter(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTFDescrTelKeyTyped

    public void LimpaTabela(){
        for(int i = 0; i<jTabelaTel.getRowCount(); i++){
           jTabelaTel.setValueAt(null, i, 0);
           jTabelaTel.setValueAt(null, i, 1);
       }
    }
        public void LimpartelaTel(){
          //Metodo que "Limpa" todas as caixas de texto no painel "Telefone"
        jTFCodigoTel.setText(null);
       jFTelefone.setText(null);
       jTFDescrTel.setText(null);
       LimpaTabela();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddTel;
    private javax.swing.JButton jBBusCod;
    private javax.swing.JButton jBBuscarTel;
    private javax.swing.JButton jBExTel;
    private javax.swing.JButton jBLimparTel;
    private javax.swing.JFormattedTextField jFTelefone;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigoTel;
    private javax.swing.JTextField jTFDescrTel;
    private javax.swing.JTable jTabelaTel;
    // End of variables declaration//GEN-END:variables
}
