/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.Array;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/**
 *
 * @author Renan
 */
public class TelaPrincipal2 extends javax.swing.JFrame {

    private int func;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal2() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth(); // Pega a largura do monitor
        int height = (int) screenSize.getHeight(); // Pega a altura do monitor
        jDesktopPane2.setSize(width, height);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemPerfil = new javax.swing.JMenuItem();
        jMenuItemTel = new javax.swing.JMenuItem();
        jMenuItemResp = new javax.swing.JMenuItem();
        jMenuRela = new javax.swing.JMenu();
        jMenuItemRelatAlu = new javax.swing.JMenuItem();
        jMenuHor = new javax.swing.JMenu();
        jMenuItemHorario = new javax.swing.JMenuItem();
        jMenuList = new javax.swing.JMenu();
        jMenuItemListadCham = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ctrl + College");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 952, -1, -1));

        jDesktopPane2.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDesktopPane2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jDesktopPane2ComponentMoved(evt);
            }
        });
        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 136, 1367, 520));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logoPequeno.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroundLaGr.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 140));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(162, 43));

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });

        jMenuItemPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONPerfil.png"))); // NOI18N
        jMenuItemPerfil.setText("Perfil");
        jMenuItemPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPerfilActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemPerfil);

        jMenuItemTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONTelefone.png"))); // NOI18N
        jMenuItemTel.setText("Telefone");
        jMenuItemTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemTel);

        jMenuItemResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONResponsavel.png"))); // NOI18N
        jMenuItemResp.setText("Responsável do Aluno");
        jMenuItemResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRespActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemResp);

        jMenuBar1.add(jMenuCadastro);

        jMenuRela.setText("Relatório de Alunos");

        jMenuItemRelatAlu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONRelatorio.png"))); // NOI18N
        jMenuItemRelatAlu.setText("Relatório de Alunos");
        jMenuItemRelatAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatAluActionPerformed(evt);
            }
        });
        jMenuRela.add(jMenuItemRelatAlu);

        jMenuBar1.add(jMenuRela);

        jMenuHor.setText("Horário");

        jMenuItemHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONHorario.png"))); // NOI18N
        jMenuItemHorario.setText("Horário");
        jMenuItemHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHorarioActionPerformed(evt);
            }
        });
        jMenuHor.add(jMenuItemHorario);

        jMenuBar1.add(jMenuHor);

        jMenuList.setText("Lista de Chamada");

        jMenuItemListadCham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONLista.png"))); // NOI18N
        jMenuItemListadCham.setText("Lista de Chamada");
        jMenuItemListadCham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadChamActionPerformed(evt);
            }
        });
        jMenuList.add(jMenuItemListadCham);

        jMenuBar1.add(jMenuList);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed
        // TODO add your handling code here:
//        TelaCadastroInternal tela = new TelaCadastroInternal();
//        jDesktopPane2.add(tela); 
//         Dimension t = Toolkit.getDefaultToolkit().getScreenSize();
//                    tela.setLocation((t.width - tela.getSize().width)/2, (t.height - tela.getSize().height)/2);
//        tela.setVisible(true);
//       
    }//GEN-LAST:event_jMenuCadastroActionPerformed

    private void jMenuItemPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPerfilActionPerformed
        // TODO add your handling code here:
        TelaCadastroInternal tela = new TelaCadastroInternal();
        tela.setFunc(func); // Passa o código do usuario que está logado, para registro de LOG.
        
        jDesktopPane2.removeAll(); // Fecha todos os frames que estão abertas.
        jDesktopPane2.updateUI();         
        
        tela.setSize(jDesktopPane2.getWidth(), jDesktopPane2.getHeight()+26); // Deixa a tela para o tamanho do DesktopPane
        tela.setLocation(0,-26); // Alinha a exibição do jFrame 
 
        jDesktopPane2.add(tela); 
        
        tela.setVisible(true);
        tela.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent ce) {
                tela.setLocation(0, -26);//To change body of generated methods, choose Tools | Templates.
            }
            
});
    }//GEN-LAST:event_jMenuItemPerfilActionPerformed

    private void jMenuItemHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHorarioActionPerformed
        // TODO add your handling code here:
        TelaHorarioInternal tela = new TelaHorarioInternal();
        tela.setFunc(func);// Passa o código do usuario que está logado, para registro de LOG.
        
         jDesktopPane2.removeAll();// Fecha todos os frames que estão abertas.
        jDesktopPane2.updateUI();
        
       tela.setSize(jDesktopPane2.getWidth(), jDesktopPane2.getHeight()+26); // Deixa a tela para o tamanho do DesktopPane
        tela.setLocation(0,-26); // Alinha a exibição do jFrame 
 
        jDesktopPane2.add(tela); // Adiciona o InternalFrame no DesktopPane;
        
        tela.setVisible(true); // Torna o frame visível 
        tela.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent ce) {
                tela.setLocation(0, -26);// Impede o movimento do frame
            }
            
});
    }//GEN-LAST:event_jMenuItemHorarioActionPerformed

    private void jMenuItemListadChamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadChamActionPerformed
        // TODO add your handling code here:
        TelaGerarListaInternal tela = new TelaGerarListaInternal();
        tela.setFunc(func);// Passa o código do usuario que está logado, para registro de LOG.
        
         jDesktopPane2.removeAll(); // Fecha todos os frames que estão abertas.
        jDesktopPane2.updateUI();
        
         tela.setSize(jDesktopPane2.getWidth(), jDesktopPane2.getHeight()+26); // Deixa a tela para o tamanho do DesktopPane
        tela.setLocation(0,-26); // Alinha a exibição do jFrame 
 
        jDesktopPane2.add(tela); // Adiciona o InternalFrame no DesktopPane;
        
        tela.setVisible(true); // Torna o frame visível
        tela.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent ce) {
                tela.setLocation(0, -26); // Impede o movimento do frame
            }
            
});
    }//GEN-LAST:event_jMenuItemListadChamActionPerformed

    private void jMenuItemRelatAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatAluActionPerformed
        // TODO add your handling code here:
        TelaBuscaInternal tela = new TelaBuscaInternal();
        tela.setFunc(func);// Passa o código do usuario que está logado, para registro de LOG.
        
         jDesktopPane2.removeAll(); // Fecha todos os frames que estão abertas.
        jDesktopPane2.updateUI();
        
        tela.setSize(jDesktopPane2.getWidth(), jDesktopPane2.getHeight()+26); // Deixa a tela para o tamanho do DesktopPane
        tela.setLocation(0,-26); // Alinha a exibição do jFrame 
 
        jDesktopPane2.add(tela); // Adiciona o InternalFrame no DesktopPane;
        
        tela.setVisible(true); // Torna o frame visível
        tela.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent ce) {
                tela.setLocation(0, -26); // Impede o movimento do frame
            }
            
});
    }//GEN-LAST:event_jMenuItemRelatAluActionPerformed

    private void jMenuItemTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelActionPerformed
        // TODO add your handling code here:
        TelaTelefoneInternal tela = new TelaTelefoneInternal();
        tela.setFunc(func);// Passa o código do usuario que está logado, para registro de LOG.
        
         jDesktopPane2.removeAll(); // Fecha todos os frames que estão abertas.
        jDesktopPane2.updateUI();
        
        tela.setSize(jDesktopPane2.getWidth(), jDesktopPane2.getHeight()+26); // Deixa a tela para o tamanho do DesktopPane
        tela.setLocation(0,-26); // Alinha a exibição do jFrame 
 
        jDesktopPane2.add(tela); // Adiciona o InternalFrame no DesktopPane;
        
        tela.setVisible(true); // Torna o frame visível
        tela.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent ce) {
                tela.setLocation(0, -26); // Impede o movimento do frame
            }
            
});
        
    }//GEN-LAST:event_jMenuItemTelActionPerformed

    private void jMenuItemRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRespActionPerformed
        // TODO add your handling code here:       
        TelaResponsavelInternal tela = new TelaResponsavelInternal();
        tela.setFunc(func);// Passa o código do usuario que está logado, para registro de LOG.
        
         jDesktopPane2.removeAll(); // Fecha todos os frames que estão abertas.
        jDesktopPane2.updateUI();
        
       tela.setSize(jDesktopPane2.getWidth(), jDesktopPane2.getHeight()+26); // Deixa a tela para o tamanho do DesktopPane
        tela.setLocation(0,-26); // Alinha a exibição do jFrame 
 
        jDesktopPane2.add(tela); // Adiciona o InternalFrame no DesktopPane;
        
        tela.setVisible(true); // Torna o frame visível
        tela.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent ce) {
                tela.setLocation(0, -26); // Impede o movimento do frame
            }
            
});
    }//GEN-LAST:event_jMenuItemRespActionPerformed

    private void jDesktopPane2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDesktopPane2ComponentMoved
        
    }//GEN-LAST:event_jDesktopPane2ComponentMoved

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal2().setVisible(true);
             
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuHor;
    private javax.swing.JMenuItem jMenuItemHorario;
    private javax.swing.JMenuItem jMenuItemListadCham;
    private javax.swing.JMenuItem jMenuItemPerfil;
    private javax.swing.JMenuItem jMenuItemRelatAlu;
    private javax.swing.JMenuItem jMenuItemResp;
    private javax.swing.JMenuItem jMenuItemTel;
    private javax.swing.JMenu jMenuList;
    private javax.swing.JMenu jMenuRela;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public int getFunc() {
        return func;
    }

    public void setFunc(int func) {
        this.func = func;
    }
}
