/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas2;

import TelasAntigas.TelaBusca2;
import Codigos.Conexao;
import Codigos.ListadeChamada;
import Codigos.Pessoa;
import Codigos.Relatorio;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Renan
 */
public class TelaBuscaInternal extends javax.swing.JInternalFrame {
    private int func;
    /**
     * Creates new form TelaBuscaInternal
     */
    public TelaBuscaInternal() {
        initComponents();
        jTabelaRegistros.setDefaultRenderer(Object.class, new CellRenderer());
        jTRelatorioTab.setDefaultRenderer(Object.class, new CellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTSala = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTRA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaRegistros = new javax.swing.JTable();
        jBBusCod = new javax.swing.JButton();
        jPRelatorio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTRelRA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTRelNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTRelSerie = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTRelatorioTab = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1367, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBuscar.setText("Buscar");
        jBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Sala Atual:");

        jTSala.setEditable(false);
        jTSala.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTSala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Aluno:");

        jTNome.setEditable(false);
        jTNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Registros");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("RA:");

        jTRA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTRA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTRA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTRAKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTRAKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTRAKeyTyped(evt);
            }
        });

        jTabelaRegistros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabelaRegistros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTabelaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Aula", "Sala", "Disciplina", "Professor", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaRegistros.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTabelaRegistros);

        jBBusCod.setText("...");
        jBBusCod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBBusCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBusCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTSala, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jTNome, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTRA, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBBusCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBusCod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTSala, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONBusca.png")), jPanel1); // NOI18N

        jPRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        jPRelatorio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("RA:");

        jTRelRA.setEditable(false);
        jTRelRA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTRelRA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nome:");

        jTRelNome.setEditable(false);
        jTRelNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTRelNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Série:");

        jTRelSerie.setEditable(false);
        jTRelSerie.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTRelSerie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTRelatorioTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTRelatorioTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Disciplina", "Total de Aulas", "Presenças", "Faltas", "%"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTRelatorioTab);

        javax.swing.GroupLayout jPRelatorioLayout = new javax.swing.GroupLayout(jPRelatorio);
        jPRelatorio.setLayout(jPRelatorioLayout);
        jPRelatorioLayout.setHorizontalGroup(
            jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRelatorioLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTRelSerie)
                    .addComponent(jTRelNome)
                    .addComponent(jTRelRA, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPRelatorioLayout.setVerticalGroup(
            jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRelatorioLayout.createSequentialGroup()
                .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRelatorioLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPRelatorioLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTRelRA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTRelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTRelSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatório", new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONRelatorio.png")), jPRelatorio); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getFunc() {
        return func;
    }

    public void setFunc(int func) {
        this.func = func;
    }

    public class CellRenderer extends DefaultTableCellRenderer {
	public CellRenderer() {
		super();
	}
	public Component getTableCellRendererComponent(JTable table, Object value,
			boolean isSelected, boolean hasFocus, int row, int column) {
		this.setHorizontalAlignment(CENTER);
		return super.getTableCellRendererComponent(table, value, isSelected,
				hasFocus, row, column);
	}
}
    
    private void limpaTabela(){ // Método que limpa todos os campos da tabela
        int i;
        for(i=0; i<17; i++){
            jTabelaRegistros.setValueAt("", i, 0);
            jTabelaRegistros.setValueAt("", i, 1);
            jTabelaRegistros.setValueAt("", i, 2);
            jTabelaRegistros.setValueAt("", i, 3);
            jTabelaRegistros.setValueAt("", i, 4);
            jTabelaRegistros.setValueAt("", i, 5);
        }
    }
    
    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        // TODO add your handling code here:
        limpaTabela();
        ListadeChamada a = new ListadeChamada();
        ListadeChamada a1 = new ListadeChamada();
        Pessoa p = new Pessoa();
        Conexao c = new Conexao();
        Relatorio r = new Relatorio();
        ArrayList<String> recente;
        int linha = 0;
        int cont = 0;

        a.setRA(Integer.parseInt(jTRA.getText()));
        a1.setRA(Integer.parseInt(jTRA.getText()));

        //String para buscar o Nome, a Série e a Sala do aluno.
        String NomedoAluno = " select a.pess_st_nome, c.serie_st_descricao, c.serie_st_sala "
        + "from pcc_tb_pessoas a, pcc_tb_aluno_serie b, pcc_tb_serie c "
        + "where c.Serie_INT_Codigo = b.Ano_INT_Codigo "
        + "and b.Aluno_INT_Codigo = a.Pess_INT_Codigo "
        + "and a.Pess_INT_Codigo = "+a.getRA()+";";

        //String para buscar os registros mais recentes do aluno.
        String MaisRecentes = "select a.Lista_DT_Data, b.Hor_INT_Aula, "
                + "c.Serie_ST_Sala, a.Lista_ST_SituacaoAluno, "
                + "e.Disc_ST_Descricao, p.Pess_ST_Nome from "
                + "pcc_tb_listachamada a, pcc_tb_horario b, pcc_tb_serie c, "
                + "pcc_tb_disciplina e, pcc_tb_pessoas p where "
                + "a.Hor_INT_Codigo = b.Hor_INT_Codigo and "
                + "b.Serie_INT_Codigo = c.Serie_INT_Codigo and"
                + " b.Disc_INT_Codigo = e.Disc_INT_Codigo AND "
                + "p.Pess_INT_Codigo = b.Pro_INT_Codigo and "
                + "a.Aluno_INT_Codigo = '"+a.getRA()+"' order by a.Lista_DT_Data DESC;";


        try {
            c.conectar(); //Conecta no banco de dados.

            p =  c.pesquisa_nome(NomedoAluno); //Pesquisa os nomes e insere nos campos de texto abaixo.

            jTRelRA.setText(String.valueOf(a.getRA()));
            jTSala.setText(p.getSala());
            jTRelNome.setText(p.getNome());
            jTRelSerie.setText(p.getSerie()); //  Preenche os campos com os dados encontrados 
            jTNome.setText(p.getNome());
            
            recente = c.pesquisa_maisrecentes(MaisRecentes); // Executa o comando de pesquisa dos dados registrados mais recentes
            int i;
            
            for(i=0; i<recente.size(); i++){ // Preenche a tabela com os dados encontrados
                String dados[] = recente.get(i).split(";");
                jTabelaRegistros.setValueAt(dados[0], i, 0);
                jTabelaRegistros.setValueAt(dados[1], i, 1);
                jTabelaRegistros.setValueAt(dados[2], i, 2);
                jTabelaRegistros.setValueAt(dados[4], i, 3);
                jTabelaRegistros.setValueAt(dados[5], i, 4);
                jTabelaRegistros.setValueAt(dados[3], i, 5);
            }

            for(linha=1;linha<=13;linha++){

                //Chama a procedure que calcula a frequencia do aluno.
                String Relatorio = "call proc_Frequencia('"+a1.getRA()+"', '"+linha+"');";

                r = c.relatorio_frequencia(Relatorio);

                //Insere os registros da procedure Frequencia na tabela da aba de relatorio.
                //(linha-1 pois não existe codigo de disciplina 0 e a tabela começa na linha 0).
                jTRelatorioTab.setValueAt(r.getMateria(), linha-1, 0);
                jTRelatorioTab.setValueAt(r.getQtdAulas(), linha-1, 1);
                jTRelatorioTab.setValueAt(r.getQtdPresecas(), linha-1, 2);
                jTRelatorioTab.setValueAt(r.getQtdFaltas(), linha-1, 3);
                jTRelatorioTab.setValueAt(r.getPorcFreq(), linha-1, 4);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaBusca2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaBusca2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBuscarActionPerformed

    private void jBBusCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBusCodActionPerformed
        // TODO add your handling code here:
        //Chama a tela (BuscaCodigo) que ajuda a encontra o código dos alunos
        TelaBuscaCodigo t = new TelaBuscaCodigo();
        t.setTipo("Aluno"); // Especifica o campo do Tipo para a pesquisa no banco de dados
        t.getCod();
        t.setVisible(true);
        
    }//GEN-LAST:event_jBBusCodActionPerformed

    private void jTRAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTRAKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jBuscar.doClick();
        }
    }//GEN-LAST:event_jTRAKeyPressed

    private void jTRAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTRAKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRAKeyReleased

    private void jTRAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTRAKeyTyped
        char vchar = evt.getKeyChar();
        //Impede que seja digitado letra no campo de pesquisa
        if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTRAKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBusCod;
    private javax.swing.JButton jBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPRelatorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTRA;
    private javax.swing.JTextField jTRelNome;
    private javax.swing.JTextField jTRelRA;
    private javax.swing.JTextField jTRelSerie;
    private javax.swing.JTable jTRelatorioTab;
    private javax.swing.JTextField jTSala;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTabelaRegistros;
    // End of variables declaration//GEN-END:variables
}
